version: "3.8"
services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: petcarex_db
    ports:
      - "1433:1433"
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "YourStrong!Passw0rd"   # đổi mạnh
    volumes:
      - mssql_data:/var/opt/mssql

volumes:
  mssql_data:

# /opt/mssql-tools18/bin/sqlcmd \
#   -S localhost \
#   -U sa \
#   -P 'YourStrong!Passw0rd' \
#   -C